version: '3'
services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "4000:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    command: redis-server --appendonly yes
  rails:
    build:
      context: ./rails
    command: bash -c "tail -f log/development.log"
    volumes:
      - ./rails:/myapp
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
    environment:
      REDIS_URL: redis://redis:6379/0
      REDIS_PORT: 6379
  next:
      build:
        dockerfile: ./next/Dockerfile
      tty: true
      stdin_open: true
      volumes:
        - ./next:/app
      ports:
        - "8001:3000"
volumes:
  mysql_data: